name: beiersdorf-remote
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - matplotlib
  - python=3.9
  - pandas
  - openpyxl
  - seaborn
  - ipywidgets
  - requests
  - beautifulsoup4
  - wordcloud
  - pip
  - pip:
    - pandas-profiling

